services:
  jupyter:
    container_name: jupyter-sec
    build: .
    user: root
    ports:
      - "8008:8008"
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.5"

    mem_limit: 2g
    cpus: 1.5

    ulimits:
      nproc: 256

    volumes:
      - ./jupyter_persist:/home/jovyan/work
      - ./jupyter_custom:/home/jovyan/.jupyter/custom
      - ./jupyter_config/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py

    environment:
      - DOCKER_STACKS_JUPYTER_CMD=nbclassic
      - NB_USER=jovyan
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=/home/jovyan/work
      - CHOWN_EXTRA_OPTS=-R
      - JUPYTER_DOCKER_STACKS_QUIET=
      - GRANT_SUDO="yes"
      - JUPYTER_ENV_VARS_TO_UNSET=
      - JUPYTER_PORT=8008
      - CHOWN_HOME_OPTS=-R
      - LD_LIBRARY_PATH=

    command: >
      start-notebook.py
      --ServerApp.root_dir=/home/jovyan/work
      --ServerApp.default_url=/tree
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.ip=0.0.0.0
